
version: "3.9"

volumes:
  postgres_data:
      driver: local

services:

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025
      - 1025:1025

  postgres:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command:
      - start-dev
