
name: ci

on: [push, pull_request]

jobs:
  ci:

    services:
      keycloak:
        image: jboss/keycloak:15.0.2
        ports:
          - 8080:8080
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
          - 8025:8025
          - 1025:1025

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: run go vet
      run: go vet ./...

    - name: test
      run: go test -race -v ./...
