
name: ci

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: run go vet
      run: go vet ./...

    - name: test
      run: |
        docker-compose up -d
        sleep 20
        go test -race -v ./...
